set windows-shell := ["powershell.exe", "-c"]

default:
    just --list

build:
    cargo build --release

format:
    cargo fmt

lint:
    cargo clippy -- -W clippy::pedantic

profile: build
    samply record ./target/release/advent-of-code-2024

run:
    cargo run --release -- solve

run-example:
    cargo run --release -- solve --input "example.txt"

run-day day:
    cargo run --release -- solve {{day}}

run-day-example day:
    cargo run --release -- solve {{day}} --input "example.txt"